### ISSUE TITLE
core lightning failure

### ISSUE THREAD

**Issue by vincenzopalazzo** [rustyrussell/lnprototest#121]
```
ERROR    root:utils.py:98 Traceback (most recent call last):
  File "/home/vincent/github/work/lnprototest/lnprototest/utils/utils.py", line 95, in run_runner
    runner.run(test)
  File "/home/vincent/github/work/lnprototest/lnprototest/runner.py", line 100, in run
    all_done = sequence.action(self)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vincent/github/work/lnprototest/lnprototest/structure.py", line 55, in action
    all_done &= e.action(runner)
                ^^^^^^^^^^^^^^^^
  File "/home/vincent/github/work/lnprototest/lnprototest/event.py", line 377, in action
    raise EventError(self, "{}: message was {}".format(err, msg.to_str()))
lnprototest.errors.EventError: `Expected msgtype-funding_signed, got msgtype-error: message was error channel_id=0000000000000000000000000000000000000000000000000000000000000000 data=426164207369676e617475726520333034353032323130306637653461303563323435333164663830343365653535363730356330376435343763396337323261383935396135333634643266353337333230343936633330323230323265353962636138353363643339653037356632396562636132353962666365363438656264393335393137346163363165366138396365366635656631323031206f6e207478203032303030303030303161333733363238333962313366363163666538326433356264333937623132363463333839623234353834376366623631313162333838393235343664633737303030303030303030306634333661393830303163313430306630303030303030303030313630303134653134326361396266633264353663643061646238326638646338373034323437363733383966373463666630303230207573696e67206b657920303364333031393964373466623561323264343762366530353465326633373863656461636666636238393930346136316437356430646264343037313433653635` on event [{"event": "ExpectMsg", "file": "ln_spec_utils.py", "pos": "197"},]
================================================== short test summary info ==================================================
FAILED tests/test_bolt2-01-close_channel.py::test_close_channel_shutdown_msg_normal_case_receiver_side - AssertionError: `Expected msgtype-funding_signed, got msgtype-error: message was error channel_id=0000000000000000000000...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Core lightning commit: 5bd3d5113137d38a0703b3ad09cf6b807b9a5c3e

**Comment by vincenzopalazzo** [comment]
More on here

```
=========================== short test summary info ============================
FAILED tests/test_bolt2-02-reestablish.py::test_reestablish - AssertionError:...
FAILED tests/test_bolt2-01-close_channel.py::test_close_channel_shutdown_msg_normal_case_receiver_side
FAILED tests/test_bolt2-01-open_channel.py::test_open_channel_from_accepter_side
FAILED tests/test_bolt2-10-add-htlc.py::test_htlc_add - lnprototest.errors.Ev...
FAILED tests/test_bolt2-01-open_channel.py::test_open_channel_opener_side - A...
FAILED tests/test_bolt2-01-open_channel.py::test_open_channel_opener_side_wrong_announcement_signatures
FAILED tests/test_bolt7-01-channel_announcement-success.py::test_gossip_forget_channel_after_12_blocks
============= 7 failed, 23 passed, 15 skipped in 89.67s (0:01:29) ==============
```

**Comment by vincenzopalazzo** [comment]
OK I isolate this one, see https://github.com/rustyrussell/lnprototest/issues/123
