### ISSUE TITLE
bolt2: failure to connect with the node, the runner did not receive `open_channel2`

### ISSUE THREAD

**Issue by vincenzopalazzo** [rustyrussell/lnprototest#54]
With the patch https://github.com/ElementsProject/lightning/pull/5367/files the issue https://github.com/rustyrussell/lnprototest/issues/31 is gone 💯 

But sometime I receive the following error

```
self = ExpectMsg:test_bolt2-20-open_channel_accepter.py:2406
runner = <lnprototest.clightning.clightning.Runner object at 0x7f7e8354bee0>

    def action(self, runner: "Runner") -> bool:
        super().action(runner)
        conn = self.find_conn(runner)
        while True:
            binmsg = runner.get_output_message(conn, self)
            if binmsg is None:
>               raise EventError(
                    self, f"Did not receive a message {self.msgtype} from runner"
                )
E               lnprototest.errors.EventError: (ExpectMsg:test_bolt2-20-open_channel_accepter.py:2406, 'Did not receive a message msgtype-open_channel2 from runner')

lnprototest/event.py:318: EventError
---------------------------------------------- Captured stdout call -----------------------------------------------
signing our input for tx 02000000022f144a38afb7c3886d18f5283a8da92e79c7f6a24a64a5c7f9d5187ac2753f360500000000fdffffff2f144a38afb7c3886d18f5283a8da92e79c7f6a24a64a5c7f9d5187ac2753f360000000000fdffffff03908201000000000016001473daa75958d5b2ddca87a6c279bb7cb30716703760df160000000000160014d640ab16f347d1de5aba5a715321a5fc4ba9a5d5d8ba0d0000000000220020c46bf3d1686d6dbb2d9244f8f67b90370c5aa2747045f1aeccb77d818711738266000000
Signing 1 redeemscript keys 03d30199d74fb5a22d47b6e054e2f378cedacffcb89904a61d75d0dbd407143e65 and 03e60fce93b59e9ec53011aabc21c23e97b2a31369b87a5ae9c44ee89e2a6dec0a: 522103d30199d74fb5a22d47b6e054e2f378cedacffcb89904a61d75d0dbd407143e652103e60fce93b59e9ec53011aabc21c23e97b2a31369b87a5ae9c44ee89e2a6dec0a52ae amount = 899800
tx: 0200000001acf33cb15a77827f6f7cfdc4d4a2d0bf8b06708f09a92b631b12f8edb1824e8102000000006d669280044a0100000000000022002047d040ee05dd47a80038faf7fa42e8559bfc8b60bd981410ad1d67d02dbe65e94a01000000000000220020c2c8616728753143bed607ea0b17e5ef615d05ada442dcd1613098597cb1ad09801a060000000000220020233d69d88092351875ce0b9fd5ea576b2307c539eaed7abdf97fbb26720f01acfc94070000000000220020673a559ef5a5f20daa54be8b9b140457e12ae37f2f507b6f4a50aea6822eaf8850e05c20
witness is ...  CTxInWitness(CScriptWitness(x('304402202141ffe3d20751b2fb2978b5ab3340086b0b9547c4cf797ec51ed1dbad4b605f02206c83c26aaa3490aa21a68f4120fddff241aebf66fee095b7e78a564c286fe39301'),x('02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5')))
witnesses are [{witness_element=[{witness=304402202141ffe3d20751b2fb2978b5ab3340086b0b9547c4cf797ec51ed1dbad4b605f02206c83c26aaa3490aa21a68f4120fddff241aebf66fee095b7e78a564c286fe39301},{witness=02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5}]}]
------------------------------------------------ Captured log call ------------------------------------------------
ERROR    concurrent.futures:_base.py:330 exception calling callback for <Future at 0x7f7e8354dd90 state=finished raised RpcError>
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/home/vincent/Github/lnprototest/lnprototest/clightning/clightning.py", line 359, in _done
    raise (exception)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/vincent/Github/lnprototest/lnprototest/clightning/clightning.py", line 345, in _run_rbf
    bump = runner.rpc.openchannel_bump(
  File "/home/vincent/.cache/pypoetry/virtualenvs/lnprototest-AvqpilGs-py3.8/lib/python3.8/site-packages/pyln/client/lightning.py", line 1051, in openchannel_bump
    return self.call("openchannel_bump", payload)
  File "/home/vincent/.cache/pypoetry/virtualenvs/lnprototest-AvqpilGs-py3.8/lib/python3.8/site-packages/pyln/client/lightning.py", line 387, in call
    raise RpcError(method, payload, resp['error'])
pyln.client.lightning.RpcError: RPC call failed: method: openchannel_bump, payload: {'channel_id': 'aa96b1189f7036d424df0081cca3f019181013f92b47668dfca1f60140370d58', 'amount': 498800, 'initialpsbt': 'cHNidP8BAFICAAAAAS8USjivt8OIbRj1KDqNqS55x/aiSmSlx/nVGHrCdT82AAAAAAD9////ATbjFgAAAAAAFgAUCdhZaR8I0hwzwR0e44WWaXkRiDsAAAAAAAEA/YUBAgAAAAABAYRZGlZyCqvIAjzs9xgBxeD50EnQxVCrQkEq0Spn2J86AAAAAAD+////B4CEHgAAAAAAFgAU/ZZY+9R20xjzuCWxUrFSqvpJvJJAQg8AAAAAABYAFINEBZYmgTLmyZ1E2uLRUdq9misjLBgKKQEAAAAWABTSlfdtojGXkfNt9XWeRbFdXhBSIcDGLQAAAAAAFgAUVNFK6RB5PpMNjjPT3gsMvwWqUzMACT0AAAAAABYAFBtC4fx7HNk6Rp+mftXqvzbONU3WIKEHAAAAAAAWABQGr9Rrzf0i75SsEiqhHyQSRKN+zICNWwAAAAAAIgAgALBo324OBULnds6l6+j18am0C1Md3Y6Usaf/mCm1u6oCRzBEAiA2e5v+0FZbrSE3Ek9zY3Nib6MTXlmyCntcHY8rjxsmuwIgL2ZN45eHCCo3bSIkh/Au8Z5FaWwEEESm1Xnuyrto6UUBIQNWYJqQSnAmxzkdP79xrZKgDgS0zS+2qNHmnLwJmPZpCmUAAAABAR+AhB4AAAAAABYAFP2WWPvUdtMY87glsVKxUqr6SbySAAA=', 'funding_feerate': '2031perkw'}, error: {'code': -1, 'message': 'Unexpected wire message 0048aa96b1189f7036d424df0081cca3f019181013f92b47668dfca1f60140370d580000000000079c7000000064000007ef'}
ERROR    concurrent.futures:_base.py:330 exception calling callback for <Future at 0x7f7e835682e0 state=finished raised RpcError>
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/home/vincent/Github/lnprototest/lnprototest/clightning/clightning.py", line 359, in _done
    raise (exception)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/vincent/Github/lnprototest/lnprototest/clightning/clightning.py", line 345, in _run_rbf
    bump = runner.rpc.openchannel_bump(
  File "/home/vincent/.cache/pypoetry/virtualenvs/lnprototest-AvqpilGs-py3.8/lib/python3.8/site-packages/pyln/client/lightning.py", line 1051, in openchannel_bump
    return self.call("openchannel_bump", payload)
  File "/home/vincent/.cache/pypoetry/virtualenvs/lnprototest-AvqpilGs-py3.8/lib/python3.8/site-packages/pyln/client/lightning.py", line 387, in call
    raise RpcError(method, payload, resp['error'])
pyln.client.lightning.RpcError: RPC call failed: method: openchannel_bump, payload: {'channel_id': 'aa96b1189f7036d424df0081cca3f019181013f92b47668dfca1f60140370d58', 'amount': 498800, 'initialpsbt': 'cHNidP8BAFICAAAAAS8USjivt8OIbRj1KDqNqS55x/aiSmSlx/nVGHrCdT82AAAAAAD9////ATbjFgAAAAAAFgAUUne/UQVzB3DqV23ok9TGrDCm23MAAAAAAAEA/YUBAgAAAAABAYRZGlZyCqvIAjzs9xgBxeD50EnQxVCrQkEq0Spn2J86AAAAAAD+////B4CEHgAAAAAAFgAU/ZZY+9R20xjzuCWxUrFSqvpJvJJAQg8AAAAAABYAFINEBZYmgTLmyZ1E2uLRUdq9misjLBgKKQEAAAAWABTSlfdtojGXkfNt9XWeRbFdXhBSIcDGLQAAAAAAFgAUVNFK6RB5PpMNjjPT3gsMvwWqUzMACT0AAAAAABYAFBtC4fx7HNk6Rp+mftXqvzbONU3WIKEHAAAAAAAWABQGr9Rrzf0i75SsEiqhHyQSRKN+zICNWwAAAAAAIgAgALBo324OBULnds6l6+j18am0C1Md3Y6Usaf/mCm1u6oCRzBEAiA2e5v+0FZbrSE3Ek9zY3Nib6MTXlmyCntcHY8rjxsmuwIgL2ZN45eHCCo3bSIkh/Au8Z5FaWwEEESm1Xnuyrto6UUBIQNWYJqQSnAmxzkdP79xrZKgDgS0zS+2qNHmnLwJmPZpCmUAAAABAR+AhB4AAAAAABYAFP2WWPvUdtMY87glsVKxUqr6SbySAAA=', 'funding_feerate': '2031perkw'}, error: {'code': -1, 'message': 'Owning subdaemon dualopend died (62208)'}
ERROR    concurrent.futures:_base.py:330 exception calling callback for <Future at 0x7f7e880247f0 state=finished raised RpcError>
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/home/vincent/Github/lnprototest/lnprototest/clightning/clightning.py", line 303, in _done
    raise exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/vincent/Github/lnprototest/lnprototest/clightning/clightning.py", line 296, in _fundchannel
    return runner.rpc.fundchannel(
  File "/home/vincent/.cache/pypoetry/virtualenvs/lnprototest-AvqpilGs-py3.8/lib/python3.8/site-packages/pyln/client/lightning.py", line 730, in fundchannel
    return self.call("fundchannel", payload)
  File "/home/vincent/.cache/pypoetry/virtualenvs/lnprototest-AvqpilGs-py3.8/lib/python3.8/site-packages/pyln/client/lightning.py", line 387, in call
    raise RpcError(method, payload, resp['error'])
pyln.client.lightning.RpcError: RPC call failed: method: fundchannel, payload: {'id': '02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5', 'amount': 499800, 'feerate': '2000perkw', 'announce': True}, error: {'code': 400, 'message': 'Unable to connect, no address known for peer', 'data': {'id': '02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5', 'method': 'connect'}}
============================================= short test summary info =============================================
FAILED tests/test_bolt2-20-open_channel_accepter.py::test_rbf_opener_forgets - lnprototest.errors.EventError: (E...

```

**Comment by vincenzopalazzo** [comment]
Reproduced in https://github.com/ElementsProject/lightning/issues/6059
